workspace:
  base: /src
  path: github.com/abramsimon/abramsimon-dotnet

pipeline:
  build_interview:
    group: build
    image: microsoft/aspnetcore-build:2.0
    commands:
      - dotnet restore
      - dotnet publish -c Release -o app
  # build_interview_ui:
  #   group: build
  #   image: node:alpine
  #   commands:
  #     - cd interview-ui/
  #     - npm install
  #     - npm run build --production

  publish_container_interview:
      image: docker:dind
      environment:
        - DOCKER_HOST=tcp://docker:2375
      commands:
        - sleep 5
        - docker ps
        - docker login -u _json_key -p "$(cat .gcr_credentials.json)" https://gcr.io
        - docker build ./interview -t grc.io/model-craft-198603/interview-api:latest
        - docker push grc.io/model-craft-198603/interview-api:latest

services:
  docker:
    image: docker:dind
    privileged: true

  # push_container_interview:
  #   image: plugins/gcr
  #   repo: abramsimon/abramsimon-dotnet
  #   dockerfile: interview/dockerfile
  #   tags: latest
  #   json_key: >
  #     {
  #       "type": "service_account",
  #       "project_id": "model-craft-198603",
  #       "private_key_id": "d50ab3a1b998e9c10488dcbb9dd0f5345e08aa9a",
  #       "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDf+gbwSL17CPyY\nE2efam12icfQglBmMsC9G0RthL5/cGByxhRFdx3CmUtOzFB9wJfM++7VQGZ8GKda\njR1Aq2Lub/Na97lhpqeGdFBLAgUhG16lSCsxOlOy3crhWgPZuqsS76XclOL9B7eb\nUv3l3zcYr/puza1VYtxfpuPNZxg61k0XhTC36qQEn+HY3mVvPHLrAFmOrfaey1cq\nFexs1LXVMI1j87xgAA87vluytj9C5d/Bb/hcIxqI6lgYWtgGL9e06s3hXDTOD8LN\nsV2etFB4DxHPP1roYNxv48x65BX/ikoaNjCCcCPa8VuiV9NJpL62L4krx2VSqjfS\ndQl8a+/pAgMBAAECggEAVX9C0MxjkCjBC2g04RSmTl6P6Ncly61KB6X1+/x1H36N\nQqK8MDwlHxiXN7AkdaxkBfqRk9PuiyZ6E8XUSdBihnQzqCDyIgWU421ZDRjrTlT9\nTwh6fGMwehHSFS3gVGe+UA8s+EPZVg9xFhibFPmdNY5PgaZ/qR2A0/6H7OuSwzo+\nCFURIeMrtnNekn1iDfHN6Vl9RFmjzHApl+7AKHKkoHt6qmkviFFNOWd8/1otzj7u\nCxD9skNP6BLhVQ32jT/FXvElbglkakR3nGyeC4jfQ+NWXkNvPeGLBG2dbWKiSohh\n3t16YZPhV3plzs3cLdd3XU0zhOIarGjdGswh1t+sNQKBgQDw/us5EsXbSHji86I1\n3gyXuskerWERNc3qeur563AdKFZzmWp+afnD5HskKhn6DflJiBCnD5/uzkywDxtk\nddKO9xkqGi5ldUibjoz/dMR9Vw0yu1jtK4d9VzKbiuKtdjAUj7gXzbJt8R8xival\nQctVg3UdZuTWXoIHz0367W4m/wKBgQDt69nwiJnDGbZRxjgeIwzXF/L4JE6qOK4e\nPzw4QHdiLDi2xGM3dTkV6Cz0uUbnmctBPR4F4PaJUQC340Uf4twgZ+BkWg48hDAN\nr4TcULCwXAkagU23P6ZpdntTbt/GkPV4kJu9NjovpvX/YwPyXWavqk5FER1h6bF9\nPpqnLJCRFwKBgAJpitE3buOTBiK/bZA8eMPMCtdTxPT3JOiD8nYt9SFVlgfyMS6y\nwN1FHDZwdXIbUbN6uS/y6Bbr2bipbgzDYSgtMQNK38wEMIXeF2s3MABRLsCjP3Cg\nTuriRI9qBHrYBAMwrRcP6AlRsI4+ZdmhnvdsKW/x57h9ma+aU51/YurhAoGAAyAv\nG87fnkWPNKHTCOpS99xzr7jiY7Ac8X7JLsACEYMdN6F64DalClmjhY+Nk+tcVT4V\nT+R1uLYcuU2+Eb4sQCy9MPRR7Y+bBgMBTtesipSa9gMu3zJx4D7TPfRd8kDjSLM1\nqJW2y/t4jeNiIOQDPlmRb6za4vdsAoY5B+s49v8CgYEAwwWL27HUyKVRHS9tCB4X\nDDRXK+JF/ZxZ3XcIMO4aFCen/HGaV57WB1z9Nign/Ib5L+CAP0gJCpMGnqvL3bEG\njwkreg+QM5yBofuAYiPRWY5C1Nj2DrKRUx0lXBVi0LYJ+grLmMtzv6E8524RXZY2\nx7Mm3kFNw/Eoc8ZJ7DBtepE=\n-----END PRIVATE KEY-----\n",
  #       "client_email": "drone-949@model-craft-198603.iam.gserviceaccount.com",
  #       "client_id": "107414972243766604060",
  #       "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  #       "token_uri": "https://accounts.google.com/o/oauth2/token",
  #       "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  #       "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/drone-949%40model-craft-198603.iam.gserviceaccount.com"
  #     }