workspace:
  base: /src
  path: github.com/abramsimon/abramsimon-dotnet

pipeline:
  build_interview:
    group: build
    image: microsoft/aspnetcore-build:2.0
    commands:
      - dotnet restore
      - dotnet publish -c Release -o app
  build_interview_ui:
    group: build
    image: node:alpine
    commands:
      - cd interview-ui/
      - npm install
      - npm run build --production
