workspace:
  base: /src
  path: github.com/abramsimon/abramsimon-dotnet

pipeline:
  build_interview:
    image: microsoft/aspnetcore-build:2.0
    commands:
      - dotnet restore
      - dotnet publish -c Release -o app
