workspace:
  base: /src
  path: github.com/abramsimon/abramsimon-dotnet

pipeline:
  build_interview:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - dotnet restore
      - dotnet publish -c Release -o app
  build_interview_ui:
    image: node:alpine
