apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: interview-deployment
  labels:
    app: interview
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interview
  template:
    metadata:
      labels:
        app: interview
    spec:
      containers:
      - name: interview-ui
        image: gcr.io/abramsimon-com/interview-ui
        ports:
        - containerPort: 5000
        tty: true
        stdin: true